version: '3'

tasks:
  default:
    cmds:
      - task --list

  format:
    desc: コードのフォーマット
    cmds:
      - uv run ruff format src tests

  lint:
    desc: コードの静的解析
    cmds:
      - uv run ruff check src tests

  test:
    desc: テストの実行
    cmds:
      - uv run pytest tests --cov=src --cov-report=term-missing --cov-branch


